
library(ggplot2)
library(data.table)


# Functions

# Calculates expected heterozygosity for model where single population splits into subpopulations (demes) with smaller pop size.
# A final population is generated by sampling from the demes.
# Two sampling schemes: 
# 1. The final population is a mixture with equal proportions from all demes ("Sampling of all demes") 
# 2. The final population is generated from a single deme ("Sampling of single deme"). 

getHeterozygosity = function(bottleneckLengthGen, NeBottleneck, NeAncestral, numDemes, numSamplesPerDeme, mutRate) {
  expectHet_withinDeme = 4*NeAncestral*mutRate*(1-1/(2*NeBottleneck))^bottleneckLengthGen
  expectHet_betweenDeme = 2*(2*NeAncestral + bottleneckLengthGen)*mutRate
  
  totalSampleSize = numDemes*numSamplesPerDeme
  totalNumComparisons = (totalSampleSize^2 - totalSampleSize)/2
  numComparisonsWithinDeme = (numSamplesPerDeme^2-numSamplesPerDeme)/2 * numDemes
  numComparisonsBetweenDeme = totalNumComparisons - numComparisonsWithinDeme
  
  expectHet_overAllDemes = numComparisonsWithinDeme/totalNumComparisons*expectHet_withinDeme + numComparisonsBetweenDeme/totalNumComparisons*expectHet_betweenDeme
  
  ret = data.table(bottleneckLengthGen = bottleneckLengthGen, NeBottleneck = NeBottleneck, NeAncestral = NeAncestral, numDemes = numDemes, numSamplesPerDeme = numSamplesPerDeme, mutRate = mutRate, Sampling = "Sampling of single deme", expectHet=expectHet_withinDeme)
  ret = rbind(ret, data.table(bottleneckLengthGen = bottleneckLengthGen, NeBottleneck = NeBottleneck, NeAncestral = NeAncestral, numDemes = numDemes, numSamplesPerDeme = numSamplesPerDeme, mutRate = mutRate, Sampling = "Sampling of all demes", expectHet=expectHet_overAllDemes))
  return(ret)
}

wrap_by <- function(...) {
  facet_wrap(vars(...), labeller = label_both)
}


# Set working directory

setwd("~/work/Adelaide/AmericanBison_Bastien/TheoreticalPrediction/")


# Run calculation of heterozygosity for various parameter values

NeAncestral = 1e5
mutRate = 2e-8

res = data.table()
for (botLen in seq(0, 50, 1)) {
  for (NeBottleneck in c(5, 20, 50, 200)) {
    for (numDemes in c(2,5,10,50)) {
      for (sampPerDeme in c(5, 10, 20, 100)) {
        res = rbind(res, getHeterozygosity(bottleneckLengthGen = botLen, NeBottleneck = NeBottleneck, NeAncestral = NeAncestral, numDemes = numDemes, numSamplesPerDeme = sampPerDeme, mutRate = mutRate))
      }
    }
  }
}


# Plot results

pdf(file="expectedHeterozygosity_predictions_BisonStructureBottlenecks.pdf", width = 5.5, height = 6)
  ggplot(data=subset(res, numSamplesPerDeme == 5)) + geom_line(aes(bottleneckLengthGen, expectHet, col=Sampling)) + wrap_by(NeBottleneck, numDemes) + theme_bw() + coord_cartesian(ylim=c(0,0.008)) + ylab("Expected heterozygosity") + xlab("Length of bottleneck in generations") +
  theme(legend.position="top", legend.direction = "vertical", legend.title=element_blank())
dev.off()



